server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: LingXi
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${LingXi.datasource.database.url}
    username: ${LingXi.datasource.database.username}
    password: ${LingXi.datasource.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化连接数
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大活跃连接数
      max-active: 20
      # 获取连接等待超时时间（毫秒）
      max-wait: 60000

      # 以下是解决你报错的关键配置
      # 开启空闲连接检查
      test-while-idle: true
      # 指定探测 SQL（MySQL 专用）
      validation-query: SELECT 1
      # 建议开启借出时检查，确保拿到的连接一定是好的
      test-on-borrow: true
      # 归还时检查（可开启，但会有一定性能开销）
      test-on-return: false

      # 定期清理任务执行的间隔（毫秒），默认 60 秒
      time-between-eviction-runs-millis: 60000
      # 连接在池中保持空闲而不被回收的最小时间
      min-evictable-idle-time-millis: 300000
  data:
    redis:
      host: ${LingXi.datasource.redis.host}
      port: ${LingXi.datasource.redis.port}
      password: ${LingXi.datasource.redis.password}
      timeout: ${LingXi.datasource.redis.timeout:10000}
      database: ${LingXi.datasource.redis.database:0}
lingxi:
  agent:
    workspace: docker
    runtime:
      tool:
        common:
          max-output: 500
        read-file:
          enabled: true
          max-output: 3000
        edit-file:
          enabled: true
          max-output: 200
        terminal:
          enabled: true
          timeout: 30
          max-output: 2000
        web-search:
          enabled: true
          baseUrl: https://api.tavily.com/search
          apiKey: ${TAVILY_APIKEY}
          timeout: 30
          max-output: 3000
          max-result: 3
        context-compact:
          enabled: true

    model:
      conf:
        chat:
          base-url: https://api.deepseek.com                        #https://openrouter.ai/api/v1/chat/completions     http://localhost:1234/v1 https://globalai.vip/v1
          api-key:  ${DEEPSEEK_APIKEY}              #  #OPENROUTER_APIKEY   GLOBALAI_APIKEY
          model-name: "deepseek-v4-flash"                            #"google/gemma-4-12b-qat" "deepseek-v4-flash" "stealth/ox-alpha"
          timeout: 120s
          max-iterations: 50
          max-tokens: 393200
          reasoning-effort: medium
        compact:
          base-url: https://globalai.vip/v1                         #https://openrouter.ai/api/v1/chat/completions  https://api.deepseek.com   http://localhost:1234/v1
          api-key: ${GLOBALAI_APIKEY}
          model-name: "deepseek-v4-flash"
          timeout: 120s
          maxTokens: 32768
          reasoning-effort: "none"
          send-thinking: false
          return-thinking: false

