LingXi:
  datasource:
    database:
      url: jdbc:mysql://${HOST}:3306/LingXi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: summit@2152938389@qq.com
      password: summit
    redis:
      host: ${HOST}
      port: 6379
