LingXi:
  datasource:
    database:
      url: jdbc:mysql://${HOST}:3306/LingXi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
    redis:
      host: ${HOST}
      port: 6379
